FROM node:alpine as build 

WORKDIR /app

COPY /package.json .

RUN npm install -g npm@7.20.0

RUN npm install --force

RUN npm install -g @angular/cli@12.1.2

COPY . .

RUN ng build

FROM nginx

EXPOSE 4200

# # Delete the default welcome to nginx page.
# RUN rm /usr/share/nginx/html/*

COPY nginx/default.conf /etc/nginx/conf.d/default.conf

COPY --from=build /app/dist/client /usr/share/nginx/html


# FROM node:12.13.0-alpine as build 
# WORKDIR /app
# COPY package*.json ./
# RUN npm install 
# COPY . .
# RUN npm run build

# FROM nginx 
# EXPOSE 3000
# COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf
# COPY --from=build /app/build /usr/share/nginx/html

