FROM node:alpine

WORKDIR '/app'

COPY /package.json .

RUN npm install -g npm@7.20.0

RUN npm install -g @angular/cli@11.2.3

COPY . .


CMD ng build

FROM nginx

EXPOSE 4200

COPY nginx/default.conf /etc/nginx/conf.d/default.conf

COPY --from=0 /app/build /usr/share/nginx/html
