FROM node:alpine

RUN apk add chromium

WORKDIR /usr/app

ENV CHROME_BIN=/usr/bin/chromium-browser

COPY /package.json .

RUN npm install -g npm@7.20.0

RUN npm install --force

RUN npm install -g @angular/cli@12.1.2

COPY . .

CMD ng serve --host 0.0.0.0 --disable-host-check