FROM node:alpine

RUN apk add chromium

WORKDIR /usr/app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

ENV CHROME_BIN=/usr/bin/chromium-browser

COPY /package.json /app/package.json

RUN npm install -g npm@7.20.0

RUN npm install -g @angular/cli@12.1.2

COPY . .

EXPOSE 4200

CMD ng serve --host 0.0.0.0 --disable-host-check